# Generated by Django 3.0 on 2019-12-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='imgUrl',
            field=models.CharField(default='#', max_length=100),
        ),
        migrations.AddField(
            model_name='app',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='app',
            name='rank',
            field=models.IntegerField(default=999),
        ),
        migrations.AlterField(
            model_name='app',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
