# Generated by Django 3.0.1 on 2019-12-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGDB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='category',
        ),
        migrations.AddField(
            model_name='app',
            name='category',
            field=models.ManyToManyField(to='MGDB.Category'),
        ),
    ]
