# Generated by Django 3.0 on 2019-12-20 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MGDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorpick',
            name='app',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='MGDB.App'),
        ),
    ]
