# Generated by Django 3.0 on 2019-12-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGDB', '0002_auto_20191220_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorpick',
            name='name',
            field=models.CharField(default='Banner', max_length=50),
        ),
    ]
