# Generated by Django 3.0 on 2019-12-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGDB', '0002_auto_20191217_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('imgUrl', models.CharField(default='#', max_length=100)),
            ],
        ),
    ]
