# Generated by Django 3.0.1 on 2019-12-21 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MGDB', '0002_auto_20191221_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='category',
        ),
        migrations.AddField(
            model_name='app',
            name='category',
            field=models.ForeignKey(default='#', on_delete=django.db.models.deletion.CASCADE, to='MGDB.Category'),
            preserve_default=False,
        ),
    ]
