# Generated by Django 3.0.1 on 2019-12-21 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MGDB', '0003_auto_20191221_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='category',
        ),
    ]
