# Generated by Django 3.0 on 2019-12-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MGDB', '0003_editorpick_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorpick',
            name='name',
        ),
    ]
