# Generated by Django 3.0 on 2019-12-19 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MGDB', '0003_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='app',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='app',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='app',
            name='rating',
        ),
        migrations.AddField(
            model_name='app',
            name='editorPick',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='app',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MGDB.Category'),
        ),
    ]
