# Generated by Django 3.0 on 2019-12-19 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGDB', '0004_auto_20191219_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
