# Generated by Django 3.0 on 2019-12-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MGDB', '0004_remove_editorpick_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='categories',
            new_name='category',
        ),
    ]
