# Generated by Django 3.0.1 on 2019-12-21 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MGDB', '0004_remove_app_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MGDB.Category'),
        ),
    ]
