# Generated by Django 3.0 on 2019-12-21 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MGDB', '0005_app_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='samplePic1',
        ),
        migrations.RemoveField(
            model_name='app',
            name='samplePic2',
        ),
        migrations.RemoveField(
            model_name='app',
            name='samplePic3',
        ),
        migrations.CreateModel(
            name='SamplePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MGDB.App')),
            ],
        ),
    ]
