# Generated by Django 3.0 on 2019-12-19 13:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MGDB', '0005_auto_20191219_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MGDB.App')),
            ],
        ),
    ]
