# Generated by Django 3.0 on 2019-12-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGDB', '0006_auto_20191221_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplepic',
            name='imgUrl',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
